baseurl: https://alivaughan.netlify.app/
title: little notes
theme: hugo-creative-portfolio-theme
languageCode: en-au
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2016 Your name or company'
  description: Describe your website
  email: ali.g.vaughan@gmail.com
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
    - name: About
      url: about/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - I am a Health Economist living in Perth (Whadjuk Noongar Boodja)
    - I have been teaching myself R and needed a place to keep little notes. Hopefully it helps others too
  social:
    github: https://github.com/AliVaughan
    twitter: https://twitter.com/AliVaughan

  style: default
